# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  docker-build:
    executor: microscanner/default
    working_directory: ~/movie-analyst-api
    steps:
      - checkout  
      # Download and cache dependencies
      - run: docker build -t circleci/node:latest .

workflows:
  version: 2.1
  scan-image:
    jobs:
      - docker-build
      - microscanner/scan-image:
          requires:
            - docker-build
          context: microscanner
          image: circleci/node:latest